#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define CIRQUE_PINNACLE_I2C
#define CIRQUE_PINNACLE_ADDRESS 0x2A
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP26
#define I2C1_SCL_PIN GP27
// I2C speed configuration (uncomment one):
//#define I2C1_CLOCK_SPEED 100000  // 100kHz (standard mode)
#define I2C1_CLOCK_SPEED 400000  // 400kHz (fast mode) - default
// #define I2C1_CLOCK_SPEED 1000000 // 1MHz (fast mode plus)
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
//#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
//#define POINTING_DEVICE_GESTURE_SCROLL_DIVISOR_H 8
//#define POINTING_DEVICE_GESTURE_SCROLL_DIVISOR_V 8
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X
